default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: todo
  user: todo
  password: todo
  host: 127.0.0.1

test:
  <<: *default
  database: todo_test
  user: todo_test
  password: todo_test 
  host: 127.0.0.1  

production:
  <<: *default
  database: todo
  user: todo
  password: todo
  host: 127.0.0.1  
